{"name": "Проверка логина c неправильным логином", "status": "passed", "description": "Пытаемся залогиниться в аккаунт пользователя, получаем ошибку 401 и соотвествующее сообщение", "start": 1723629944681, "stop": 1723629944989, "uuid": "7bc613b3-a937-439d-8aa3-8a9334f86c3b", "historyId": "163fbac4a50b86dea237f47a01dd012d", "testCaseId": "163fbac4a50b86dea237f47a01dd012d", "fullName": "tests.test_login_user.TestLoginUser#test_no_such_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-NE0EJ4CA"}, {"name": "thread", "value": "8424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}